[package]
name = "libzcashlc"
version = "0.0.5"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "rust/build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
zcash_client_backend = "0.4"
zcash_client_sqlite = "0.2.1"
zcash_primitives = { version = "0.4", features = ["transparent-inputs"] }

#### Temporary additions: ####################################
base58 = "0.1.0"
sha2 = "0.9"
bs58 = { version = "0.3", features = ["check"] }
hdwallet = "0.2.2"
ripemd160 = "0.9"
secp256k1 = "0.17.2"
time = "0.2"
##############################################################


[dependencies.zcash_proofs]
version = "0.4"
default-features = false
features = ["local-prover"]

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "rust/src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[patch.crates-io]
zcash_client_backend = {git = "https://github.com/pacu/librustzcash", branch = "autoshield-poc" }
zcash_client_sqlite = {git = "https://github.com/pacu/librustzcash", branch = "autoshield-poc" }
zcash_primitives = {git = "https://github.com/pacu/librustzcash", branch = "autoshield-poc" }
zcash_proofs = {git = "https://github.com/pacu/librustzcash", branch = "autoshield-poc" }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]

[patch.crates-io]
zcash_client_backend = { git = 'https://github.com/zcash/librustzcash', rev = 'c289cf9d4b46d330c265006e5f796543f2744fe5' } 
zcash_client_sqlite = { git = 'https://github.com/zcash/librustzcash', rev = 'c289cf9d4b46d330c265006e5f796543f2744fe5' }
zcash_primitives = { git = 'https://github.com/zcash/librustzcash', rev = 'c289cf9d4b46d330c265006e5f796543f2744fe5' }
zcash_proofs = { git = 'https://github.com/zcash/librustzcash', rev = 'c289cf9d4b46d330c265006e5f796543f2744fe5' }
